# https://hub.docker.com/_/alpine

FROM nginx:alpine
LABEL org.opencontainers.image.authors="githubfoam"

WORKDIR /tmp

## Make a copy of default configuration file 
# and change listen port to 8080
RUN cp /etc/nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf.orig && \
    sed -i 's/listen[[:space:]]*80;/listen 8080;/g' /etc/nginx/conf.d/default.conf

EXPOSE 8080

CMD ["nginx", "-g", "daemon off;"]
