# https://hub.docker.com/_/alpine
FROM alpine:3.14
LABEL org.opencontainers.image.authors="githubfoam"


RUN apk --update add git less openssh && \
    rm -rf /var/lib/apt/lists/* && \
    rm /var/cache/apk/*

# Create user and set ownership and permissions as required
RUN mkdir myapp-data && adduser -D myuser && chown -R myuser /myapp-data

WORKDIR /tmp

RUN apk add --no-cache mysql-client

USER myuser


ENTRYPOINT ["mysql"]
