# https://hub.docker.com/_/alpine
FROM alpine:latest
LABEL org.opencontainers.image.authors="githubfoam"


RUN apk --update add git less openssh && \
    rm -rf /var/lib/apt/lists/* && \
    rm /var/cache/apk/*

# Create user and set ownership and permissions as required
RUN mkdir myapp-data && adduser -D myuser && chown -R myuser /myapp-data

USER myuser

WORKDIR /tmp